(() => {
"use strict";
const KEY="timeline-party-language";let lang=localStorage.getItem(KEY)==="en-US"?"en-US":"da-DK";const originals=new WeakMap();
const exact={
"Spilkode":"Game code","Del koden med de andre spillere.":"Share the code with the other players.","Forbinder igen":"Reconnecting","Genoptager spil…":"Resuming game…","Vi finder din spiller og din tidslinje.":"We are finding your player and timeline.","Opret eller deltag i et spil":"Create or join a game","Dit navn":"Your name","Navn":"Name","Opret spil":"Create game","Deltag i spil":"Join game","Indtast spilkode":"Enter game code","Spillere":"Players","Spilmenu":"Game menu",
"Spilindstillinger":"Game settings","Kortrettelser":"Card corrections","Statistik":"Statistics","Afslut spil og vis vinder":"End game and show winner","Spillet er slut":"Game over","Slutstilling":"Final standings","Spil revanche":"Play again","Vinder":"Winner",
"Min profil":"My profile","Spilhistorik":"Game history","Tidligere spil":"Previous games","Vælg avatar":"Choose avatar","Gem profil":"Save profile","Luk":"Close","Ingen tidligere spil endnu.":"No previous games yet.","Seneste spil":"Recent games","Bedste score":"Best score","Samlede point":"Total points","Gns. point pr. spil":"Avg. points per game","Træfsikkerhed":"Accuracy","Sejrsrate":"Win rate","Korrekte svar":"Correct answers","Afsluttede spil":"Completed games",
"Spillere i lobbyen":"Players in the lobby","Invitér spillere":"Invite players","Kopiér spilkode":"Copy game code","Kopieret":"Copied","Klar":"Ready","Online":"Online","Offline":"Offline","Venter på at værten starter en sang.":"Waiting for the host to start a song.",
"Først til point":"First to points","Fast antal runder":"Fixed number of rounds","Værten afslutter":"Host ends game","Point for sejr":"Points to win","Antal runder":"Number of rounds","Challenges pr. spiller":"Challenges per player","Challenges slået til":"Challenges enabled","Svar-timer i sekunder (0 = fra)":"Answer timer in seconds (0 = off)","Gem indstillinger":"Save settings","Spiltype":"Game type","Svar-timer":"Answer timer","Ingen timer":"No timer",
"Rettede Hitster-kort":"Corrected Hitster cards","Ingen lokale rettelser endnu.":"No local corrections yet.","Slet":"Delete","Nulstil statistik":"Reset statistics","Kort":"Card","Rettet år":"Corrected year","Oprindeligt år":"Original year",
"Start sang":"Start song","Næste sang":"Next song","Afslør svar":"Reveal answer","Lås svar":"Lock answer","Challenge":"Challenge","Pas":"Pass","Forlad spillet":"Leave game","Afslut spillet":"End game","Start forfra":"Restart game","Start runden":"Start round","Svar":"Answer","Vælg placering":"Choose placement","Vælg årti":"Choose decade","Bekræft":"Confirm","Vent på de andre spillere":"Wait for the other players","Venter på":"Waiting for",
"Scan Hitster-kort":"Scan Hitster card","Luk scanner":"Close scanner","Brug denne sang":"Use this song","Kopiér QR-data":"Copy QR data","Titel":"Title","Kunstner":"Artist","År":"Year","Link":"Link","Scan QR-koden på bagsiden af Hitster-kortet.":"Scan the QR code on the back of the Hitster card.","Peg kameraet mod QR-koden.":"Point the camera at the QR code.",
"Vært":"Host","Din tur":"Your turn","Point":"Points","Tidslinje":"Timeline","Se tidslinje":"View timeline","Luk tidslinje":"Close timeline","Ikke mulig":"Unavailable","Før":"Before","Efter":"After","Mellem":"Between","Første sang":"First song","Gæt årti":"Guess decade","Placér sangen":"Place the song","Du har låst dit svar.":"You locked your answer.","Dit svar er låst.":"Your answer is locked.","Du kan challenge":"You can challenge","Du har ingen challenges tilbage.":"You have no challenges left.","Challenge er ikke mulig.":"Challenge is unavailable.",
"Korrekt svar!":"Correct answer!","Forkert svar":"Incorrect answer","Ingen ramte denne gang.":"No one got it right this time.","Svaret er afsløret":"The answer is revealed","Spillet er afsluttet":"The game is over","Sangen er placeret på tidslinjen.":"The song was added to the timeline.","Ingen fik sangen.":"No one won the song.","Næste spiller":"Next player","Runden er slut":"Round complete","Afventer vært":"Waiting for host",
"Spotify tilsluttet":"Spotify connected","Tilslut Spotify":"Connect Spotify","Afbryd Spotify":"Disconnect Spotify","Afspil":"Play","Pause":"Pause","Afspiller":"Playing","Forbinder til Spotify…":"Connecting to Spotify…","Spotify er ikke tilsluttet":"Spotify is not connected","Åbn Spotify":"Open Spotify",
"Vil du starte spillet forfra? Point, tidslinjer og challenges nulstilles.":"Restart the game? Scores, timelines, and challenges will be reset.","Vil du forlade spillet?":"Leave the game?","Vil du afslutte spillet for alle spillere?":"End the game for all players?","Skriv dit navn først.":"Enter your name first.","Skriv både navn og spilkode.":"Enter both your name and the game code.","Der er ikke forbindelse til spilserveren endnu. Vent et øjeblik og prøv igen.":"The game server is not connected yet. Wait a moment and try again.","Værten har afsluttet spillet.":"The host ended the game.","Forbindelsen er midlertidigt afbrudt. Vi prøver automatisk igen…":"The connection was temporarily lost. We are reconnecting automatically…",
"Denne browser understøtter ikke kameraadgang.":"This browser does not support camera access.","QR-scanneren kunne ikke indlæses. Kontrollér internetforbindelsen og prøv igen.":"The QR scanner could not load. Check your internet connection and try again.","Kameraadgang blev afvist. Tillad kameraet i browserens indstillinger og prøv igen.":"Camera access was denied. Allow camera access in your browser settings and try again.","Kameraet kunne ikke startes. Kontrollér, at det ikke bruges af en anden app.":"The camera could not start. Make sure another app is not using it.","QR-koden blev læst, men den ligner ikke et dansk Hitster-kort.":"The QR code was read, but it does not look like a Danish Hitster card.","QR-data kunne ikke kopieres automatisk. Markér teksten og kopiér den manuelt.":"QR data could not be copied automatically. Select the text and copy it manually."
};
const patterns=[
[/^Runde (\d+)$/,"Round $1"],[/^Runde (\d+) · (.+)s tur$/,"Round $1 · $2's turn"],[/^Spilkode: (.+)$/,"Game code: $1"],[/^Vinder: (.+)$/,"Winner: $1"],[/^(\d+) point$/,"$1 points"],[/^(\d+) runder$/,"$1 rounds"],[/^(\d+) spil$/,"$1 games"],[/^(\d+) sejre$/,"$1 wins"],[/^(\d+) gemte runder$/,"$1 saved rounds"],[/^(\d+) afsluttede spil$/,"$1 completed games"],[/^(\d+) sek\. tilbage$/,"$1 sec. left"],[/^(.+) fører med (\d+) point$/,"$1 leads with $2 points"],[/^(.+) har turen$/,"$1's turn"],[/^(.+)s tidslinje$/,"$1's timeline"],[/^(.+) har låst sit svar\.$/,"$1 locked their answer."],[/^Venter på (.+)$/,"Waiting for $1"],[/^Kort (\d+)$/,"Card $1"],[/^Hitster-kort (\d+) er ikke i vores verificerede sangliste endnu\.$/,"Hitster card $1 is not in our verified song list yet."],[/^(\d+)\/(\d+) korrekte$/,"$1/$2 correct"],[/^(\d+)% korrekte$/,"$1% correct"],[/^(.+) (\d+)p$/,"$1 $2 pts"],[/^(.+) · (\d+) point$/,"$1 · $2 points"],[/^(.+) vandt med (\d+) point$/,"$1 won with $2 points"]
];
function tr(text){if(lang!=="en-US")return text;const lead=text.match(/^\s*/)?.[0]||"",tail=text.match(/\s*$/)?.[0]||"",core=text.trim();if(!core)return text;let out=exact[core];if(!out){for(const [re,rep] of patterns){if(re.test(core)){out=core.replace(re,rep);break}}}return lead+(out||core)+tail}
function translateNode(node){if(node.nodeType===Node.TEXT_NODE){if(!originals.has(node))originals.set(node,node.nodeValue);node.nodeValue=lang==="da-DK"?originals.get(node):tr(originals.get(node));return}if(node.nodeType!==Node.ELEMENT_NODE||node.matches("script,style"))return;for(const attr of ["placeholder","title","aria-label"]){if(node.hasAttribute(attr)){const k=`attr:${attr}`,store=node.__tpOriginals||(node.__tpOriginals={});if(!(k in store))store[k]=node.getAttribute(attr);node.setAttribute(attr,lang==="da-DK"?store[k]:tr(store[k]))}}node.childNodes.forEach(translateNode)}
function apply(){document.documentElement.lang=lang==="en-US"?"en":"da";translateNode(document.body);renderSwitcher()}
function renderSwitcher(){let el=document.querySelector("#language-switcher");if(!el){el=document.createElement("div");el.id="language-switcher";el.innerHTML='<button type="button" data-lang="da-DK">🇩🇰 Dansk</button><button type="button" data-lang="en-US">🇺🇸 English</button>';document.body.appendChild(el)}el.querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang))}
document.addEventListener("click",e=>{const b=e.target.closest("#language-switcher [data-lang]");if(!b)return;lang=b.dataset.lang;localStorage.setItem(KEY,lang);apply()},true);
const nativeAlert=window.alert.bind(window),nativeConfirm=window.confirm.bind(window);window.alert=m=>nativeAlert(tr(String(m)));window.confirm=m=>nativeConfirm(tr(String(m)));
new MutationObserver(ms=>{if(ms.some(m=>m.addedNodes.length||m.type==="characterData"))requestAnimationFrame(apply)}).observe(document.documentElement,{childList:true,subtree:true,characterData:true});if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",apply);else apply();
})();