(() => {
  "use strict";

  const SIGNAL_URL = "https://timeline-party-video-signal-6-10.onrender.com";
  const GAME_CODE_KEY = "timeline-party-game-code", PLAYER_ID_KEY = "timeline-party-player-id", NAME_KEY = "timeline-party-name", AUTO_VIDEO_KEY = "timeline-party-video-auto-start";
  const MAX_VIDEO_PARTICIPANTS = 10, peers = new Map(), peerMeta = new Map(), peerRecoveryTimers = new Map(), levels = new Map();
  let signal=null, localStream=null, screenStream=null, joined=false, joining=false, joinedRoom="", focusId=null;
  let cameraEnabled=true, micEnabled=true, facingMode="user", minimized=false, activeSpeakerId=null, autoStartTriedCode="";
  let gameplayActive=false, autoMinimized=false, userLeftVideo=false, signalState="idle", audioContext=null, meterTimer=null;
  let turnPlayerId="", turnPlayerName="", challengerIds=new Set();

  const en=()=>localStorage.getItem("timeline-party-language")==="en-US", t=(da,us)=>en()?us:da;
  const myId=()=>localStorage.getItem(PLAYER_ID_KEY)||"", myName=()=>localStorage.getItem(NAME_KEY)||t("Spiller","Player");
  const gameCode=()=>String(localStorage.getItem(GAME_CODE_KEY)||"").trim().toUpperCase(), autoStartEnabled=()=>localStorage.getItem(AUTO_VIDEO_KEY)==="1";
  const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
  const initials=n=>String(n||"?").trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()).join("")||"?";
  const getVideoTrack=()=>localStream?.getVideoTracks?.()[0]||null, getAudioTrack=()=>localStream?.getAudioTracks?.()[0]||null;
  const playerIdFor=(id,local=false)=>local?myId():(peerMeta.get(id)?.playerId||"");
  const isTurn=(id,local=false)=>Boolean(turnPlayerId&&playerIdFor(id,local)===turnPlayerId);
  const isChallenger=(id,local=false)=>challengerIds.has(playerIdFor(id,local));

  async function ensureLocalMedia(){
    if(localStream)return localStream;
    if(!navigator.mediaDevices?.getUserMedia)throw new Error(t("Kamera understøttes ikke i denne browser.","Camera is not supported in this browser."));
    try{localStream=await navigator.mediaDevices.getUserMedia({video:{facingMode,width:{ideal:480},height:{ideal:270},frameRate:{ideal:18,max:20}},audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}})}
    catch{try{localStream=await navigator.mediaDevices.getUserMedia({audio:true,video:false});cameraEnabled=false}catch{throw new Error(t("Kamera/mikrofon-adgang blev afvist.","Camera/microphone access was denied."))}}
    if(getVideoTrack())getVideoTrack().enabled=cameraEnabled;if(getAudioTrack())getAudioTrack().enabled=micEnabled;return localStream;
  }
  function setSignalState(next){if(signalState!==next){signalState=next;renderVideoRoom()}}
  function closeAllPeers(){for(const timer of peerRecoveryTimers.values())clearTimeout(timer);peerRecoveryTimers.clear();peers.forEach(({pc})=>{try{pc.close()}catch{}});peers.clear();peerMeta.clear();levels.clear();activeSpeakerId=null}
  function emitJoin(room,done){signal?.emit("video:join",{room,playerId:myId(),name:myName()},done)}

  async function joinVideo({quiet=false}={}){
    const room=gameCode();if(!room||joined||joining)return;userLeftVideo=false;joining=true;signalState="connecting";renderVideoRoom();
    try{
      await ensureLocalMedia();
      signal=globalThis.io(SIGNAL_URL,{transports:["websocket","polling"],timeout:20000,reconnection:true,reconnectionAttempts:Infinity,reconnectionDelay:800,reconnectionDelayMax:5000,randomizationFactor:.35});bindSignal();
      await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(t("Videoforbindelsen svarede ikke.","The video connection did not respond."))),25000);
        signal.on("connect_error",err=>{if(!signal?.active){clearTimeout(timer);reject(err)}});
        signal.on("connect",()=>emitJoin(room,result=>{clearTimeout(timer);if(!result?.ok){if(result?.reason==="room-full")return reject(new Error(t("Videorummet har allerede 10 deltagere.","The video room already has 10 participants.")));return reject(new Error(t("Kunne ikke åbne videorummet.","Could not open the video room.")))}
          joined=true;joining=false;joinedRoom=room;signalState="connected";closeAllPeers();(result.peers||[]).forEach(meta=>{peerMeta.set(meta.socketId,meta);createPeer(meta.socketId,true)});sendPresence();startAudioMeter();adaptVideoQuality();if(gameplayActive){minimized=true;autoMinimized=true}renderVideoRoom();resolve()}));});
    }catch(error){joining=false;signalState="failed";if(!quiet)alert(error?.message||t("Video kunne ikke startes.","Video could not be started."));leaveVideo(false,{userInitiated:false});renderVideoRoom()}
  }

  function bindSignal(){
    signal.on("video:peer-joined",meta=>{peerMeta.set(meta.socketId,meta);createPeer(meta.socketId,false);adaptVideoQuality();renderVideoRoom()});
    signal.on("video:peer-left",({socketId})=>removePeer(socketId,true));
    signal.on("video:presence",meta=>{peerMeta.set(meta.socketId,{...(peerMeta.get(meta.socketId)||{}),...meta});renderVideoRoom()});
    signal.on("video:signal",async({from,playerId,name,data})=>{peerMeta.set(from,{...(peerMeta.get(from)||{}),socketId:from,playerId,name});const pc=createPeer(from,false);try{if(data.description){await pc.setRemoteDescription(data.description);if(data.description.type==="offer"){const answer=await pc.createAnswer();await pc.setLocalDescription(answer);signal.emit("video:signal",{target:from,data:{description:pc.localDescription}});await tunePeer(pc)}}else if(data.candidate)await pc.addIceCandidate(data.candidate)}catch(error){console.warn("Timeline Party video signal error",error)}});
    signal.on("disconnect",()=>{if(userLeftVideo||!joined)return;signalState="reconnecting";for(const entry of peers.values())if(entry.state==="connected")entry.state="disconnected";renderVideoRoom()});
    signal.on("connect",()=>{if(joined&&!userLeftVideo&&joinedRoom)rejoinAfterSignalReconnect()});
    signal.io?.on("reconnect_attempt",()=>{if(joined&&!userLeftVideo)setSignalState("reconnecting")});
    signal.io?.on("reconnect_failed",()=>{if(joined&&!userLeftVideo)setSignalState("failed")});
  }
  function rejoinAfterSignalReconnect(){const room=joinedRoom||gameCode();if(!room||userLeftVideo)return;setSignalState("reconnecting");emitJoin(room,result=>{if(!result?.ok)return setSignalState("failed");closeAllPeers();(result.peers||[]).forEach(meta=>{peerMeta.set(meta.socketId,meta);createPeer(meta.socketId,true)});sendPresence();adaptVideoQuality();signalState="connected";renderVideoRoom()})}

  function createPeer(socketId,initiator){
    if(peers.has(socketId))return peers.get(socketId).pc;
    const pc=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"},{urls:"stun:stun1.l.google.com:19302"}]});const entry={pc,stream:new MediaStream(),state:"connecting",recoveryAttempts:0};peers.set(socketId,entry);
    (localStream?.getTracks?.()||[]).forEach(track=>pc.addTrack(track,localStream));pc.onicecandidate=e=>e.candidate&&signal?.emit("video:signal",{target:socketId,data:{candidate:e.candidate}});
    pc.ontrack=e=>{entry.stream=e.streams?.[0]||entry.stream;if(!e.streams?.[0])entry.stream.addTrack(e.track);entry.state="connected";renderVideoRoom();startAudioMeter()};
    pc.onconnectionstatechange=()=>{entry.state=pc.connectionState;if(pc.connectionState==="connected"){entry.recoveryAttempts=0;const timer=peerRecoveryTimers.get(socketId);if(timer)clearTimeout(timer);peerRecoveryTimers.delete(socketId)}else if(["failed","disconnected"].includes(pc.connectionState))schedulePeerRecovery(socketId);else if(pc.connectionState==="closed")return removePeer(socketId,false);renderVideoRoom()};
    pc.oniceconnectionstatechange=()=>{if(["failed","disconnected"].includes(pc.iceConnectionState))schedulePeerRecovery(socketId)};if(initiator)setTimeout(()=>makeOffer(socketId,false),50);return pc;
  }
  async function makeOffer(socketId,iceRestart){const entry=peers.get(socketId);if(!entry||!signal?.connected)return;try{if(iceRestart&&entry.pc.restartIce)entry.pc.restartIce();const offer=await entry.pc.createOffer(iceRestart?{iceRestart:true}:undefined);await entry.pc.setLocalDescription(offer);signal.emit("video:signal",{target:socketId,data:{description:entry.pc.localDescription}});await tunePeer(entry.pc)}catch(error){console.warn("Timeline Party peer offer error",error)}}
  function schedulePeerRecovery(socketId){const entry=peers.get(socketId);if(!entry||peerRecoveryTimers.has(socketId))return;entry.state="disconnected";const delay=Math.min(2500+entry.recoveryAttempts*1800,8000);peerRecoveryTimers.set(socketId,setTimeout(async()=>{peerRecoveryTimers.delete(socketId);const current=peers.get(socketId);if(!current||current.pc.connectionState==="connected")return;current.recoveryAttempts+=1;if(signal?.connected){await makeOffer(socketId,true);if(current.recoveryAttempts<4)schedulePeerRecovery(socketId);else{current.state="failed";renderVideoRoom()}}else schedulePeerRecovery(socketId)},delay))}
  async function tunePeer(pc){const total=1+peers.size,videoBps=total>=9?160000:total>=7?220000:total>=5?320000:500000;for(const sender of pc.getSenders?.()||[]){if(!sender.track||!sender.getParameters||!sender.setParameters)continue;try{const params=sender.getParameters();params.encodings=params.encodings?.length?params.encodings:[{}];if(sender.track.kind==="video"){params.encodings[0].maxBitrate=videoBps;params.encodings[0].maxFramerate=total>=7?15:20}else if(sender.track.kind==="audio")params.encodings[0].maxBitrate=32000;await sender.setParameters(params)}catch{}}}
  function adaptVideoQuality(){for(const{pc}of peers.values())tunePeer(pc)}
  function removePeer(id,render=true){const timer=peerRecoveryTimers.get(id);if(timer)clearTimeout(timer);peerRecoveryTimers.delete(id);const e=peers.get(id);if(e)try{e.pc.close()}catch{}peers.delete(id);peerMeta.delete(id);levels.delete(id);if(focusId===id)focusId=null;if(activeSpeakerId===id)activeSpeakerId=null;adaptVideoQuality();if(render)renderVideoRoom()}
  function sendPresence(){signal?.emit("video:presence",{camera:cameraEnabled,microphone:micEnabled,sharing:Boolean(screenStream)})}
  function toggleCamera(){const track=getVideoTrack();if(track){cameraEnabled=!cameraEnabled;track.enabled=cameraEnabled;sendPresence();renderVideoRoom()}}
  function toggleMic(){const track=getAudioTrack();if(track){micEnabled=!micEnabled;track.enabled=micEnabled;sendPresence();renderVideoRoom()}}
  async function flipCamera(){if(!localStream||!navigator.mediaDevices?.getUserMedia||screenStream)return;const old=getVideoTrack();if(!old)return;const nextFacing=facingMode==="user"?"environment":"user";try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:nextFacing,width:{ideal:480},height:{ideal:270},frameRate:{ideal:18,max:20}},audio:false}),next=s.getVideoTracks()[0];next.enabled=cameraEnabled;for(const{pc}of peers.values()){const sender=pc.getSenders().find(x=>x.track?.kind==="video");if(sender)await sender.replaceTrack(next)}localStream.removeTrack(old);old.stop();localStream.addTrack(next);facingMode=nextFacing;adaptVideoQuality();renderVideoRoom()}catch{}}
  async function toggleShare(){if(screenStream)return stopShare();if(!navigator.mediaDevices?.getDisplayMedia)return alert(t("Skærmdeling understøttes ikke på denne enhed.","Screen sharing is not supported on this device."));try{screenStream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});const track=screenStream.getVideoTracks()[0];for(const{pc}of peers.values()){const sender=pc.getSenders().find(s=>s.track?.kind==="video");if(sender)await sender.replaceTrack(track)}track.onended=stopShare;sendPresence();renderVideoRoom()}catch{}}
  async function stopShare(){if(!screenStream)return;screenStream.getTracks().forEach(x=>x.stop());screenStream=null;const track=getVideoTrack();for(const{pc}of peers.values()){const sender=pc.getSenders().find(s=>s.track?.kind==="video"||!s.track);if(sender&&track)await sender.replaceTrack(track)}adaptVideoQuality();sendPresence();renderVideoRoom()}

  function startAudioMeter(){if(!joined||meterTimer)return;try{audioContext=audioContext||new(window.AudioContext||window.webkitAudioContext)()}catch{return}const analyzers=new Map(),add=(id,stream)=>{if(!stream?.getAudioTracks?.().length||analyzers.has(id))return;try{const source=audioContext.createMediaStreamSource(stream),an=audioContext.createAnalyser();an.fftSize=256;source.connect(an);analyzers.set(id,{an,data:new Uint8Array(an.frequencyBinCount)})}catch{}};meterTimer=setInterval(()=>{if(!joined)return;add("local",localStream);for(const[id,e]of peers)add(id,e.stream);let best=null,bestLevel=8;for(const[id,o]of analyzers){o.an.getByteFrequencyData(o.data);const level=o.data.reduce((a,b)=>a+b,0)/o.data.length;levels.set(id,level);if(level>bestLevel){best=id;bestLevel=level}}if(best&&best!==activeSpeakerId){activeSpeakerId=best;document.querySelectorAll(".video-tile").forEach(n=>n.classList.toggle("speaking",n.dataset.videoId===best));updateMiniSpeaker()}},350)}
  function stopAudioMeter(){if(meterTimer)clearInterval(meterTimer);meterTimer=null;levels.clear();activeSpeakerId=null}
  function leaveVideo(removeUi=true,{preserveMedia=false,userInitiated=true}={}){userLeftVideo=userInitiated;try{signal?.emit("video:leave");signal?.disconnect()}catch{}signal=null;joined=false;joining=false;joinedRoom="";focusId=null;minimized=false;autoMinimized=false;signalState="idle";stopAudioMeter();closeAllPeers();screenStream?.getTracks?.().forEach(x=>x.stop());screenStream=null;if(!preserveMedia){localStream?.getTracks?.().forEach(x=>x.stop());localStream=null}if(removeUi)renderVideoRoom()}
  function stateText(state){if(state==="connected")return t("forbundet","connected");if(state==="disconnected")return t("forbinder igen","reconnecting");if(state==="failed")return t("forbindelse mistet","connection lost");return t("forbinder","connecting")}
  function signalText(){if(signalState==="reconnecting")return t("Video forbinder igen… spillet fortsætter normalt.","Video is reconnecting… gameplay continues normally.");if(signalState==="failed")return t("Videoforbindelsen er ustabil. Spillet fortsætter normalt.","Video connection is unstable. Gameplay continues normally.");return ""}

  function tileHtml(id,name,local,meta,entry){
    const camera=local?cameraEnabled:meta?.camera!==false,mic=local?micEnabled:meta?.microphone!==false,sharing=local?Boolean(screenStream):Boolean(meta?.sharing),state=local?"connected":entry?.state||"connecting",turn=isTurn(id,local),challenger=isChallenger(id,local);
    const role=turn?t("🎯 HAR TUREN","🎯 ON TURN"):challenger?t("⚡ CHALLENGER","⚡ CHALLENGER"):"";
    return `<div class="video-tile ${focusId===id?"focused":""} ${activeSpeakerId===id?"speaking":""} ${turn?"turn-player":""} ${challenger?"challenger":""}" data-video-id="${esc(id)}"><div class="video-media">${role?`<span class="video-role-badge">${role}</span>`:""}<video data-video-stream="${esc(id)}" autoplay playsinline ${local?"muted":""}></video><div class="video-avatar">${esc(initials(name))}</div></div><div class="video-tile-bar"><span><strong>${esc(name)}</strong>${local?` <small>${t("(dig)","(you)")}</small>`:""}<small class="video-state-label"> · ${esc(stateText(state))}</small></span><span class="video-icons">${sharing?"🖥️":""} ${camera?"📹":"🚫"} ${mic?"🎙️":"🔇"} <i class="video-dot ${esc(state)}"></i></span></div><button class="video-focus-button" type="button" data-video-action="focus" data-id="${esc(id)}">⛶</button></div>`;
  }
  function preferredMiniId(){if(turnPlayerId===myId())return "local";for(const[id,meta]of peerMeta)if(meta?.playerId===turnPlayerId&&peers.has(id))return id;if(activeSpeakerId&&((activeSpeakerId==="local")||peers.has(activeSpeakerId)))return activeSpeakerId;return peers.keys().next().value||"local"}
  function miniSpeakerHtml(){const id=preferredMiniId(),local=id==="local",meta=local?null:peerMeta.get(id),name=local?myName():(meta?.name||t("Spiller","Player")),turn=isTurn(id,local);return `<div class="video-mini-speaker" data-mini-id="${esc(id)}"><div class="video-mini-media ${turn?"turn-player":""}"><video data-video-mini-stream="${esc(id)}" autoplay playsinline ${local?"muted":""}></video><div class="video-avatar">${esc(initials(name))}</div></div><div class="video-mini-name"><strong>${esc(name)}</strong><small>${turn?t("🎯 Har turen","🎯 On turn"):gameplayActive?t("Aktiv taler","Active speaker"):t("Videochat","Video chat")}</small></div></div>`}
  function updateMiniSpeaker(){if(!minimized)return;const holder=document.querySelector(".video-mini-wrap");if(holder){holder.innerHTML=miniSpeakerHtml();attachMiniStream()}}

  function renderVideoRoom(){
    document.querySelector(".video-room")?.remove();const code=gameCode();if(!code)return;if(joined&&joinedRoom!==code)leaveVideo(false,{userInitiated:false});const root=document.querySelector("#app");if(!root)return;const section=document.createElement("section");section.className=`card video-room ${joined?"active":"inactive"} ${minimized?"minimized":""}`;
    const autoText=autoStartEnabled()?t("Auto-video: til","Auto video: on"):t("Auto-video: fra","Auto video: off"),connectionNotice=signalText()?`<div class="video-connection-notice" role="status">⚠️ ${esc(signalText())}</div>`:"";
    if(!joined)section.innerHTML=`<div class="video-room-head"><div><h2>📹 ${t("Videochat","Video chat")}</h2><p class="hint">${t("Valgfri video og lyd mellem op til 10 spillere.","Optional video and audio for up to 10 players.")}</p></div><button type="button" class="secondary video-auto-button" data-video-action="auto">${esc(autoText)}</button></div>${connectionNotice}<button type="button" data-video-action="join" ${joining?"disabled":""}>📹 ${joining?t("Forbinder…","Connecting…"):t("Start videochat","Start video chat")}</button>`;
    else{const count=1+peers.size,remote=[...peers.entries()].sort(([a],[b])=>Number(isTurn(b,false))-Number(isTurn(a,false))||Number(isChallenger(b,false))-Number(isChallenger(a,false))),tiles=[tileHtml("local",myName(),true,{}, {state:"connected"})].concat(remote.map(([id,e])=>tileHtml(id,peerMeta.get(id)?.name||t("Spiller","Player"),false,peerMeta.get(id),e))).join(""),turnHint=gameplayActive&&turnPlayerName?t(` · ${turnPlayerName} har turen`,` · ${turnPlayerName} is on turn`):"";section.innerHTML=`<div class="video-room-head"><div><h2>📹 ${t("Videochat","Video chat")}</h2><p class="hint">${count}/${MAX_VIDEO_PARTICIPANTS} ${count===1?t("deltager","participant"):t("deltagere","participants")}${esc(turnHint)}</p></div><div class="video-head-actions"><button type="button" class="secondary" data-video-action="auto">${esc(autoText)}</button><button type="button" class="secondary" data-video-action="minimize">${minimized?"▣ "+t("Vis alle","Show all"):"— "+t("Minimér","Minimize")}</button><button type="button" class="secondary video-leave" data-video-action="leave">${t("Forlad video","Leave video")}</button></div></div>${connectionNotice}${minimized?`<div class="video-mini-wrap">${miniSpeakerHtml()}</div>`:`<div class="video-content"><div class="video-grid video-count-${Math.min(count,10)}">${tiles}</div><div class="video-controls"><button type="button" data-video-action="mic">${micEnabled?"🎙️":"🔇"} ${micEnabled?t("Mikrofon","Microphone"):t("Mikrofon fra","Microphone off")}</button><button type="button" data-video-action="camera">${cameraEnabled?"📹":"🚫"} ${cameraEnabled?t("Kamera","Camera"):t("Kamera fra","Camera off")}</button><button type="button" data-video-action="flip">🔄 ${t("Vend kamera","Flip camera")}</button><button type="button" data-video-action="share" ${navigator.mediaDevices?.getDisplayMedia?"":"disabled"}>🖥️ ${screenStream?t("Stop deling","Stop sharing"):t("Del skærm","Share screen")}</button></div></div>`}`}
    const anchor=document.querySelector(".experience-lobby")||document.querySelector(".hero-card")||root.firstElementChild;if(anchor)anchor.after(section);else root.prepend(section);if(joined){attachStreams();attachMiniStream()}
  }
  function attachStreams(){const local=document.querySelector('video[data-video-stream="local"]');if(local)local.srcObject=screenStream||localStream;for(const[id,e]of peers){const v=[...document.querySelectorAll("video[data-video-stream]")].find(n=>n.dataset.videoStream===id);if(v&&v.srcObject!==e.stream)v.srcObject=e.stream}}
  function attachMiniStream(){const v=document.querySelector("video[data-video-mini-stream]");if(!v)return;const id=v.dataset.videoMiniStream;if(id==="local")v.srcObject=screenStream||localStream;else{const stream=peers.get(id)?.stream;if(stream&&v.srcObject!==stream)v.srcObject=stream}}
  function decorate(){const code=gameCode();if(!code){autoStartTriedCode="";if(joined)leaveVideo(false,{userInitiated:false});document.querySelector(".video-room")?.remove();return}if(!document.querySelector(".video-room"))renderVideoRoom();if(autoStartEnabled()&&!joined&&!joining&&autoStartTriedCode!==code&&!userLeftVideo){autoStartTriedCode=code;setTimeout(()=>joinVideo({quiet:true}),300)}}
  function syncGameplayVideo(event){const detail=event?.detail||{};gameplayActive=Boolean(detail.active);turnPlayerId=detail.activePlayerId||"";turnPlayerName=detail.activePlayerName||"";challengerIds=new Set(detail.challengerIds||[]);if(!joined)return;if(gameplayActive&&!minimized){minimized=true;autoMinimized=true;renderVideoRoom();return}if(!gameplayActive&&minimized&&autoMinimized){minimized=false;autoMinimized=false;renderVideoRoom();return}renderVideoRoom()}
  function recoverAfterForeground(){if(document.visibilityState!=="visible"||!joined||userLeftVideo)return;if(signal&&!signal.connected){setSignalState("reconnecting");try{signal.connect()}catch{}return}for(const[id,entry]of peers)if(entry.pc.connectionState!=="connected")schedulePeerRecovery(id);if(audioContext?.state==="suspended")audioContext.resume?.().catch(()=>{})}

  document.addEventListener("click",e=>{const b=e.target.closest("[data-video-action]");if(!b)return;e.preventDefault();const a=b.dataset.videoAction;if(a==="join")joinVideo();if(a==="leave")leaveVideo();if(a==="mic")toggleMic();if(a==="camera")toggleCamera();if(a==="flip")flipCamera();if(a==="share")toggleShare();if(a==="minimize"){minimized=!minimized;autoMinimized=false;renderVideoRoom()}if(a==="focus"){focusId=focusId===b.dataset.id?null:b.dataset.id;renderVideoRoom()}if(a==="auto"){const enabled=!autoStartEnabled();localStorage.setItem(AUTO_VIDEO_KEY,enabled?"1":"0");userLeftVideo=false;if(enabled)autoStartTriedCode="";renderVideoRoom();decorate()}},true);
  document.addEventListener("visibilitychange",recoverAfterForeground);window.addEventListener("pageshow",recoverAfterForeground);window.addEventListener("online",recoverAfterForeground);document.addEventListener("timeline-party-game-phase",syncGameplayVideo);document.addEventListener("timeline-party-language-change",renderVideoRoom);window.addEventListener("beforeunload",()=>leaveVideo(false,{userInitiated:false}));new MutationObserver(()=>requestAnimationFrame(decorate)).observe(document.querySelector("#app")||document.documentElement,{childList:true,subtree:true});setInterval(decorate,1500);decorate();
})();